version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/src/*"
      - "/tests/*"
      - "/tools/*"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      dotnet:
        patterns: ["*"]
    commit-message:
      prefix: build

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
