<Project>
    <PropertyGroup>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <Deterministic>true</Deterministic>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <NuGetAudit>true</NuGetAudit>
        <NuGetAuditLevel>low</NuGetAuditLevel>
        <NuGetAuditMode>all</NuGetAuditMode>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(CI)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
        <RestoreLockedMode>true</RestoreLockedMode>
    </PropertyGroup>

    <!-- The global property also suppresses symbols from project references in the MSIX. -->
    <PropertyGroup Condition="'$(DistributionMode)' == 'Msix'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
    </PropertyGroup>
</Project>
